name: Generate Release APK

on:
  push:
    branches:
      - main  # Trigger on merges to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Java 17 using zulu
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'  # Use the zulu distribution
        java-version: '17'

    # Step 3: Set up Flutter (Use Flutter 3.24.5)
    - name: Set up Flutter 3.24.5
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'  # Use your specified version of Flutter

    # Step 4: Install dependencies
    - name: Install dependencies
      run: flutter pub get

    # Step 5: Build the release APK using Flutter command
    - name: Build Release APK
      run: flutter build apk --release

    # Step 6: Upload the Release APK as an artifact
    - name: Upload Release APK
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
