name: Generate Release APK

on:
  push:
    branches:
      - main  # Trigger on merges to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Flutter (Use a specific version)
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5' # Specify a specific version of Flutter

    # Step 3: Install dependencies
    - name: Install dependencies
      run: flutter pub get

    # Step 4: Build the release APK using Flutter command
    - name: Build Release APK
      run: flutter build apk --release

    # Step 5: Upload the Release APK as an artifact
    - name: Upload Release APK
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
